main.c File Reference
This file contains function the main function, which creates tasks, and runs the scheduler.
#include <stdlib.h>
*
#include <stdio.h>
*
#include <avr/io.h>
*
#include <avr/wdt.h>
*
#include <string.h>
*
#include <avr/interrupt.h>
*
#include `FreeRTOS.h`
*
#include `task.h`
*
#include `queue.h`
*
#include `croutine.h`
*
#include `semphr.h`
*
#include `priorities.h`
*
#include `shares.h`
*
#include `task_orient.h`
*
#include `task_comms.h`
*
#include `task_sensors.h`
*
#include `task_motors.h`
*
#include `task_safety.h`
*
#include `task_master.h`
*
#include `uart.h`
*
Functions
void task_heartbeat (void *pvParameters)
The heartbeat task simply blinks an LED to show that the system is running.
int main (void)
ISR (PCINT0_vect)
This ISR updates the motors position when a pin change interrupt has occured as a result of a change in the encoder output waveforms.
Detailed Description
This file contains function the main function, which creates tasks, and runs the scheduler. Revisions:
11-27-2014 JF, ML, JR created original file
License: This file is copyright 2012 by JF, ML, JR and released under the Lesser GNU Public License, version 2. It intended for educational use only, but its use is not limited thereto.
Definition in file main.c.
Function Documentation
int main (void)
The main function sets up the RTOS. Some test tasks are created. Then the scheduler is started up; the scheduler runs until power is turned off or there's a reset.
Returns
This is a real-time microcontroller program which doesn't return. Ever.
Definition at line 83 of file main.c.
References encoders_init(), task_comms(), task_heartbeat(), task_master(), task_motor1(), task_motor2(), task_orient(), task_safety(), and task_sensors().