task_orient.c File Reference
This file contains functions for calculating desired orientation.
#include <avr/io.h>
*
#include <avr/interrupt.h>
*
#include `FreeRTOS.h`
*
#include `task.h`
*
#include `queue.h`
*
#include `croutine.h`
*
#include `semphr.h`
*
#include `shares.h`
*
#include `task_orient.h`
*
#include `twi.h`
*
Functions
void HMC5883_init (void)
This function initializes the HMC5883 magnetometer.
void HMC5883_read (void)
This function reads HMC5883 magnetometer data into shared variables.
void task_orient (void *pvParameters)
This task function reads sensor data, and calculates the desired mirror angle.
Variables
uint8_t x_h_SHARED
These are the magnetometer position variables.
uint8_t x_l_SHARED
uint8_t z_h_SHARED
uint8_t z_l_SHARED
uint8_t y_h_SHARED
uint8_t y_l_SHARED
Detailed Description
This file contains functions for calculating desired orientation. The functions within this file are associated with the orientation algorithm, the magnetometer drivers, and the RTC drivers. Functionality to determine the correct angle based on the target position, and command the motors to get there are contained here.
Revisions:
11-27-2014 JF, ML, JR created original file
License: This file is copyright 2012 by JF, ML, JR and released under the Lesser GNU Public License, version 2. It intended for educational use only, but its use is not limited thereto.
Definition in file task_orient.c.
Function Documentation
void HMC5883_read (void)
This function reads HMC5883 magnetometer data into shared variables.
This function uses shared variables, and should therefore only be called when the calling task's priority set very high, or from within a critical section.
Definition at line 71 of file task_orient.c.
References twi_read(), twi_start(), twi_stop(), twi_write(), and x_h_SHARED.
Referenced by task_orient().
void task_orient (void * pvParameters)
This task function reads sensor data, and calculates the desired mirror angle.
This function wakes up every four minutes, determines time based on RTC sensor, determines heading with the magnetometer, calculates the angle of the sun, calculates the desired angle of the mirror array, commands that the array track the calculated angle, and blocks itself for another four minutes. The priority is set to max, since HMC5883_read accesses a shared variable.
Definition at line 97 of file task_orient.c.
References HMC5883_init(), and HMC5883_read().
Referenced by main().