task_sensors.c File Reference
This file contains functions for the ADCs, joystick, and buttons.
#include <avr/io.h>
*
#include <avr/interrupt.h>
*
#include `FreeRTOS.h`
*
#include `task.h`
*
#include `queue.h`
*
#include `croutine.h`
*
#include `semphr.h`
*
#include `shares.h`
*
#include `task_sensors.h`
*
#include `twi.h`
*
Functions
void adc_init (void)
This Function prompts the AVR I2C device to read one or more bytes.
uint16_t adc_read (uint8_t adc_channel)
This Function reads a byte from the selected ADC channel.
uint8_t button_pressed (void)
This Function detects whether or not a button has been pressed.
void button_init (void)
This function initializes the `Target Set` button.
void task_sensors (void *pvParameters)
This is the task function for monitoring the button and joysticks.
Variables
xSemaphoreHandle adc_mutex_semaphore
uint8_t btn_SHARED
Detailed Description
This file contains functions for the ADCs, joystick, and buttons. Revisions:
11-27-2014 JF, ML, JR created original file
License: This file is copyright 2012 by JF, ML, JR and released under the Lesser GNU Public License, version 2. It intended for educational use only, but its use is not limited thereto.
Definition in file task_sensors.c.
Function Documentation
void adc_init (void)
This Function prompts the AVR I2C device to read one or more bytes.
This Function prompts the I2C device to read data from the I2C data lines in master receiver mode. If the argument `lastbit` is 0, then after receiving the last byte of information, the acknowledge bit is not pulled low - this indicates the end of the transmission. If `lastbit` is set to 1, the acknowledge bit will be sent, and the I2C device will continue to read data.
Parameters
lastbit This tells the function whether or not pull the i2c/twi data lines low for an `ACK` condition.
Returns
Returns the single byte of recieved data.This function initializes the ADC on the ATMEGA 1284p.
Definition at line 56 of file task_sensors.c.
Referenced by task_sensors().
uint16_t adc_read (uint8_t adc_channel)
This Function reads a byte from the selected ADC channel.
Parameters
adc_channel Takes one of the #define macros from task_sensors.h as a parameter, for the purpose of selecting one of the ADC channels.
Returns
Returns and unsigned 16bit data value.
Use a mutex to control access to the ADC.
Definition at line 71 of file task_sensors.c.
Referenced by task_safety(), and task_sensors().
uint8_t button_pressed (void)
This Function detects whether or not a button has been pressed.
This function performs a software debounce, and updates a shared variable(btn_SHARED) when a level change is detected, indicating that the button has been pressed.
Returns
Returns the status of the button level.
Definition at line 99 of file task_sensors.c.
Referenced by task_sensors().
void task_sensors (void * pvParameters)
This is the task function for monitoring the button and joysticks.
This function monitors the `Target Set` button, and when it is pressed, updates shared variables `motor1_power_SHARED`, and `motor2_power_SHARED` with adc_channel readings. If the button is NOT pressed, the motor power shareds are set to the effective `zero power` value of 512.(1024 adc values corresponding to full forward(1023), and full reverse(0);
Definition at line 159 of file task_sensors.c.
References adc_init(), adc_read(), button_init(), and button_pressed().
Referenced by main().