task_motors.h File Reference
This file contains #defines and function declarations for motor tasks.
Macros
#define STACK_SIZE_MOTORS 280
#define IN_A_M1 PB0
#define IN_B_M1 PB1
#define EN_AB_M1 PB2
#define PWM_M1 PD5
#define IN_A_M2 PC4
#define IN_B_M2 PC5
#define EN_AB_M2 PC6
#define PWM_M2 PD4
#define ENC_A_M1 PA0
#define ENC_B_M1 PA1
#define ENC_A_M2 PA2
#define ENC_B_M2 PA3
#define PWR_LIMIT_M1 150
#define PWR_LIMIT_M2 350
Functions
void encoders_init (void)
This function initializes both motor encoders.
void motors_init (void)
This function initializes both motors.
void motor1_power (int16_t power)
This function sets the power level for motor 1.
void motor2_power (int16_t power)
This function sets the power level for motor 2.
void task_motor1 (void *pvParameters)
This is the task function for motor 1.
void task_motor2 (void *pvParameters)
This is the task function for motor 2.
Detailed Description
This file contains #defines and function declarations for motor tasks. Revisions:
11-27-2014 JF, ML, JR created original file
License: This file is copyright 2012 by JF, ML, JR and released under the Lesser GNU Public License, version 2. It intended for educational use only, but its use is not limited thereto.
Definition in file task_motors.h.
Function Documentation
void encoders_init (void)
This function initializes both motor encoders.
This function initializes all of the required pins, variables, and interrupts necessary to use the quadrature encoders.
Definition at line 60 of file task_motors.c.
Referenced by main().
void motor1_power (int16_t power)
This function sets the power level for motor 1.
This function converts a signed integer into a pwm signal and direction command for the vnh5019 motor driver chips.
Parameters
power The signed 16-bit integer corresponding to the magnitude and direction of power applied to the motors.
Definition at line 127 of file task_motors.c.
Referenced by task_motor1().
void motor2_power (int16_t power)
This function sets the power level for motor 2.
This function converts a signed integer into a pwm signal and direction command for the vnh5019 motor driver chips.
Parameters
power The signed 16-bit integer corresponding to the magnitude and direction of power applied to the motors.
Definition at line 161 of file task_motors.c.
Referenced by task_motor2().
void motors_init (void)
This function initializes both motors.
This function initializes all required pins and variables for the motors, and also initializes timer 1 to generate an output pwm signal for both motor controllers.
Definition at line 86 of file task_motors.c.
Referenced by task_motor1(), and task_motor2().
void task_motor1 (void * pvParameters)
This is the task function for motor 1.
This function decides, based on the system state, which control signal gets to set the power level of motor 1. System state is decided/updated in task_master.
Definition at line 193 of file task_motors.c.
References motor1_power(), and motors_init().
Referenced by main().
void task_motor2 (void * pvParameters)
This is the task function for motor 2.
This function decides, based on the system state, which control signal gets to set the power level of motor 2. System state is decided in task_master.
Definition at line 269 of file task_motors.c.
References motor2_power(), and motors_init().
Referenced by main().