task_motors.c File Reference
This file contains functions for motor drivers, encoders, and the motor tasks.
#include <avr/io.h>
*
#include `FreeRTOS.h`
*
#include `task.h`
*
#include `queue.h`
*
#include `croutine.h`
*
#include `semphr.h`
*
#include `uart.h`
*
#include `pid.h`
*
#include `shares.h`
*
#include `task_motors.h`
*
#include `math.h`
*
#include `task_master.h`
*
Functions
void encoders_init (void)
This function initializes both motor encoders.
void motors_init (void)
This function initializes both motors.
void motor1_power (int16_t power)
This function sets the power level for motor 1.
void motor2_power (int16_t power)
This function sets the power level for motor 2.
void task_motor1 (void *pvParameters)
This is the task function for motor 1.
void task_motor2 (void *pvParameters)
This is the task function for motor 2.
Variables
volatile uint8_t int_occurred
int16_t motor1_power_SHARED
int16_t motor2_power_SHARED
volatile int16_t position_M2_SHARED
volatile int16_t position_M1_SHARED
volatile uint16_t error_M1_SHARED
volatile uint16_t error_M2_SHARED
int16_t position_cmd_M1_SHARED
int16_t position_cmd_M2_SHARED
int16_t position_targ_init_SHARED
Detailed Description
This file contains functions for motor drivers, encoders, and the motor tasks. Revisions:
11-27-2014 JF, ML, JR created original file
License: This file is copyright 2012 by JF, ML, JR and released under the Lesser GNU Public License, version 2. It intended for educational use only, but its use is not limited thereto.
Definition in file task_motors.c.
Function Documentation
void encoders_init (void)
This function initializes both motor encoders.
This function initializes all of the required pins, variables, and interrupts necessary to use the quadrature encoders.
Definition at line 60 of file task_motors.c.
Referenced by main().
void motor1_power (int16_t power)
This function sets the power level for motor 1.
This function converts a signed integer into a pwm signal and direction command for the vnh5019 motor driver chips.
Parameters
power The signed 16-bit integer corresponding to the magnitude and direction of power applied to the motors.
Definition at line 127 of file task_motors.c.
Referenced by task_motor1().
void motor2_power (int16_t power)
This function sets the power level for motor 2.
This function converts a signed integer into a pwm signal and direction command for the vnh5019 motor driver chips.
Parameters
power The signed 16-bit integer corresponding to the magnitude and direction of power applied to the motors.
Definition at line 161 of file task_motors.c.
Referenced by task_motor2().
void motors_init (void)
This function initializes both motors.
This function initializes all required pins and variables for the motors, and also initializes timer 1 to generate an output pwm signal for both motor controllers.
Definition at line 86 of file task_motors.c.
Referenced by task_motor1(), and task_motor2().
void task_motor1 (void * pvParameters)
This is the task function for motor 1.
This function decides, based on the system state, which control signal gets to set the power level of motor 1. System state is decided/updated in task_master.
Definition at line 193 of file task_motors.c.
References motor1_power(), and motors_init().
Referenced by main().
void task_motor2 (void * pvParameters)
This is the task function for motor 2.
This function decides, based on the system state, which control signal gets to set the power level of motor 2. System state is decided in task_master.
Definition at line 269 of file task_motors.c.
References motor2_power(), and motors_init().
Referenced by main().